#!/bin/sh
PROJECTNAME=$1
HTPASSWD_USER=$2
HTPASSWD_PASS=$3
ROOT_USER_PASS=$4
DEV_USER_PASS=$5
MYSQL_ROOT_PASSWORD=$6
MYSQL_DATABASE=$7
MYSQL_USER=$8
MYSQL_PASSWORD=$9

cat << EOF
# ==============================
# GLOBAL
# ==============================
PROJECT_NAME=$PROJECTNAME

# ==============================
# WEB
# ==============================
#PHP
PHP_VERSION=stable
MAX_EXECUTION_TIME=0
MAX_INPUT_TIME=0
MAX_INPUT_VARS=1500
MEMORY_LIMIT=-1
POST_MAX_SIZE=0
UPLOAD_MAX_FILESIZE=2048M
DATE_TIMEZONE=America/Los_Angeles

#APACHE
SERVER_NAME=localhost
DOCUMENT_ROOT=/var/www/html
DIRECTORY_PERMISSION=775
FILE_PERMISSION=664
SKIP_PERMISSIONS=false
INCLUDE_HTPASSWD=true
HTPASSWD_USER=$HTPASSWD_USER
HTPASSWD_PASS=$HTPASSWD_PASS

#USERS
ROOT_USER_PASS=$ROOT_USER_PASS
DEV_USER_PASS=$DEV_USER_PASS

#CUSTOM
BUILD_FILES=false

# ==============================
# MYSQL
# ==============================
MYSQL_VERSION=stable

MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
MYSQL_DATABASE=$MYSQL_DATABASE
MYSQL_USER=$MYSQL_USER
MYSQL_PASSWORD=$MYSQL_PASSWORD
#MYSQL_ALLOW_EMPTY_PASSWORD=yes

# ==============================
# GITHUB REPOSITORY
# ==============================
#GITHUB_USER=bryanlittlefield
#GITHUB_USER_PASS=mypass123
#GITHUB_REPO_NAME=TUGBOAT